# Generated by Django 5.1.4 on 2026-06-08 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("valuations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StageReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("legal", "Legal"),
                            ("social", "Social"),
                            ("technical", "Technical"),
                            ("general", "General"),
                            ("final_approval", "Final approval"),
                            ("revert", "Revert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("reverted", "Reverted"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("ai_flags", models.JSONField(blank=True, default=list)),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valuation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_reviews",
                        to="valuations.valuation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "unique_together": {("valuation", "stage")},
            },
        ),
    ]
