# Generated by Django 5.1.4 on 2026-06-08 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0001_initial"),
        ("masters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Valuation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted for verification"),
                            ("in_verification", "In Verification"),
                            ("approved", "Approved"),
                            ("reverted", "Reverted to valuer"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("locality", models.CharField(blank=True, max_length=200)),
                (
                    "assigned_valuer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valuations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valuation",
                        to="leads.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("audio", "Audio"),
                            ("photo", "Photo"),
                            ("document", "Document"),
                            ("sketch", "Sketch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("s3_key", models.CharField(max_length=500)),
                ("mime", models.CharField(blank=True, max_length=120)),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("size", models.BigIntegerField(blank=True, null=True)),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Seconds, for audio", null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("uploaded", models.BooleanField(default=False)),
                (
                    "transcript",
                    models.JSONField(
                        blank=True, help_text="{text, language, english}", null=True
                    ),
                ),
                (
                    "extraction",
                    models.JSONField(
                        blank=True,
                        help_text="Structured fields from doc/photo analysis",
                        null=True,
                    ),
                ),
                (
                    "valuation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="valuations.valuation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarketRateLookup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.TextField()),
                (
                    "result_range",
                    models.JSONField(
                        blank=True, help_text="{min, max, unit, currency}", null=True
                    ),
                ),
                ("citations", models.JSONField(blank=True, default=list)),
                ("raw_response", models.JSONField(blank=True, null=True)),
                (
                    "valuation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_rates",
                        to="valuations.valuation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.JSONField(blank=True, null=True)),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("green", "Green (high)"),
                            ("amber", "Amber (review)"),
                            ("red", "Red (missing/low)"),
                        ],
                        default="red",
                        max_length=10,
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("ai_filled", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masters.question",
                    ),
                ),
                (
                    "valuation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="valuations.valuation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
                "unique_together": {("valuation", "question")},
            },
        ),
    ]
