# Generated by Django 5.1.4 on 2026-06-08 21:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valuations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredBlob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=500, unique=True)),
                ("data", models.BinaryField()),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.BigIntegerField(default=0)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
